# -*- coding: utf-8 -*-
"""bidenScraper_TRUE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qtfp7yOzYfoOp02kQ5awVSSjQ8ZwlV-h
"""

import snscrape.modules.twitter as sntwitter
import csv
import string
from datetime import timedelta, date

def daterange(start_date, end_date):
    for n in range(int((end_date - start_date).days)):
        yield start_date + timedelta(n)

start_date = date(2020, 11, 3)
end_date = date(2020, 11, 4)

for each_date in daterange(start_date, end_date):
    since = each_date.strftime("%Y-%m-%d")
    until = (each_date+timedelta(1)).strftime("%Y-%m-%d")
    keyword = ('Biden-{a}'.format(a=(each_date.strftime("%B").lower())))#Change to 'Biden' to 'Trump'
    max_tweets = 15000

#Open/create a file to append data to
    csvFile = open('{a}{b}.csv'.format(a=keyword,b=since), 'a', newline='', encoding='utf8')

#Use csv writer
    csvWriter = csv.writer(csvFile)
    csvWriter.writerow(['created_at','tweet_id','tweet','retweet_count', 'like_count','quote count',
                        'source','verified_stat','username','user_loc', 'user_created_at']) 

    for i,tweet in enumerate(sntwitter.TwitterSearchScraper(keyword + 'since:{a} until:{b} lang:en -filter:links -filter:replies'.format(a=since,b=until)).get_items()):
            if i > max_tweets :
                break      
            csvWriter.writerow([tweet.date, tweet.id, tweet.renderedContent, tweet.retweetCount, tweet.likeCount, tweet.quoteCount,
                                tweet.sourceLabel, tweet.user.verified, tweet.user.username, tweet.user.location, tweet.user.created])
    csvFile.close()

